python_begin/django/django-project/first_project/first_app/urls.py
from django.urls import path
from . import views

app_name = 'first_app'
urlpatterns = [
#     path('', views.index, name='index'),
#     # question_id -> pk
#     path('<int:pk>/', views.detail, name='detail'),
#     path('<int:pk>/results/', views.results, name='results'),
#     path('<int:question_id>/vote/', views.vote, name='vote'),

    
    path('', views.IndexView.as_view(), name='index'),
    # question_id -> pk
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    ]

python_begin/django/django-project/first_project/first_project/urls.py
from django.contrib import admin
from django.urls import path, include
# from visual_data.views import main_view

urlpatterns = [
    path('first_app/', include('first_app.urls')),
    path('admin/', admin.site.urls),
    path('visual_data/',include('visual_data.urls')),
]

python_begin/django/django-project/first_project/visual_data/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.main_view, name='index'),
    ]

python_begin/django/django-project/first_project/first_app/models.py
from datetime import datetime
from secrets import choice
from django.db import models
from django.utils import timezone


# Create your models here.

# В нашем приложении для опросов мы создадим две модели: и . 
# есть вопрос и дата публикации.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

python_begin/django/django-project/first_project/visual_data/models.py
from django.db import models

# Create your models here.

class VisData(models.Model):
    item = models.CharField(max_length=50)
    price = models.FloatField()

    def __str__(self):
        return str(self.item)

python_begin/django/django-project/first_project/first_app/views.py
# from urllib import response
from django.urls import reverse
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.views import generic

# from django.template import loader

from .models import Question , Choice

# Create your views here.
#______________________________________________________________________________________
# def index(request):
#     # return HttpResponse("Че-то впервые создал")
#     lates_question_list = Question.objects.order_by('-pub_date')[:5]
#     # output = ', '.join([q.question_text for q in lates_question_list])
#     template = loader.get_template('first_app/index.html')
#     context = {
#         'latest_question_list': lates_question_list
#     }

#     return HttpResponse(template.render(context, request))

# def index(request):
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#     context = {'latest_question_list': latest_question_list}
#     return render(request, 'first_app/index.html', context)

class IndexView(generic.ListView):
    template_name = 'first_app/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.order_by('-pub_date')[:5]

#______________________________________________________________________________________
# def detail(request, question_id):
#     return HttpResponse("You're looking at question %s." %question_id)

# def detail(request, question_id):
#     try:
#         question = Question.objects.get(pk=question_id)
#     except Question.DoesNotExist:
#         raise Http404("Question does not exits")
#     return render (request, 'first_app/detail.html', {'question' :question} )

# def detail(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'first_app/detail.html', {'question': question})

class DetailView(generic.DetailView):
    model = Question
    template_name = 'first_app/detail.html'

#______________________________________________________________________________________

# def results(request, question_id):
#     response = "You're looking at the results if questions %s."
#     return HttpResponse(response % question_id)

# def results(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'first_app/results.html',
#     {'question' : question})

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'first_app/results.html'
#______________________________________________________________________________________

# def vote(request, question_id):
#     return HttpResponse("You're voiting on questios %s." % question_id) 

def vote(request, question_id):
    question = get_object_or_404(Question, pk = question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except(KeyError, Choice.DoesNotExist):
        return render(request, 'first_app/detail.html',{
            'question' : question,
            'error_message' : "You didn't select a choice."
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('first_app:results', args = (question.id, )))

python_begin/django/django-project/first_project/visual_data/views.py
from django.shortcuts import render
from .models import VisData
from .utils import get_plot
# Create your views here.

def main_view(request):
    qs = VisData.objects.all()
    x = [x.item for x in qs]
    y = [y.item for y in qs]
    chart = get_plot(x, y)
    return render(request, 'visual_data/main.html', {'chart': chart})

python_begin/django/django-project/first_project/first_app/templates/first_app/detail.html
{% comment %} {{ question }} {% endcomment %}

{% comment %} <h1>{{ question.question_text }}</h1>
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }}</li>
{% endfor %}
</ul> {% endcomment %}

<form action="{% url 'first_app:vote' question.id %}" method="post">
{% csrf_token %}
<fieldset>
    <legend><h1>{{ question.question_text }}</h1></legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
</fieldset>
<input type="submit" value="Vote">
</form>

python_begin/django/django-project/first_project/first_app/templates/first_app/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        {% comment %} <li><a href="/first_app/{{ question.id }}/">{{ question.question_text }}</a></li> {% endcomment %}
        <li><a href="{% url 'first_app:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

python_begin/django/django-project/first_project/first_app/templates/first_app/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'first_app:detail' question.id %}">Vote again?</a>

python_begin/django/django-project/first_project/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Visual Data</title>
    </head>
    <body>
        <div class="container mt-3">
            {% block content%}
            {% endblock content %}

        </div>
    </body>
</html>

python_begin/django/django-project/first_project/visual_data/templates/visual_data/main.html
{% extends "base.html" %}

{% block content %}
    {% if chart %}
        <img src="data:image/png;base64, {{chart|safe}}"/>

    {% endif %}
{% endblock content%}